### ISSUE TITLE
unresolved external symbol _libkml_unzAttach

### ISSUE THREAD

**Issue by gambr** [google/libkml#8]
Dear All,
I built libkml-master (from msvc/libkml.sln), then I tried to build the examples (from msvc\examples\examples.sln) but I get the error:

libkmlbase.lib(zip_file.obj) : error LNK2001: unresolved external symbol _libkml_unzAttach

In fact zip_file.cc calls libkml_unzAttach() twice but that function is not declared.

Regards,
Gianni

**Comment by rashadkm** [comment]
for windows, msvc i could only enable static build due to some issues with uriparser.
the source code can be found in this link 
https://github.com/libkml/libkml/releases

**Comment by gambr** [comment]
Thanks, I will give a look at libkml/libkml

**Comment by ghost** [comment]
@gambr I found this is caused by minizip.lib compile problem(too old), we can use vs to recompile in libkml\third_party\zlib-1.2.3\contrib\minizip\minizip.sln, there is a vs solution hide here：）
Then use the new minizip_static.lib for debug and release, then example project work well.
